# Generated by Django 6.0.1 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tienda', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('tiene_stock', models.BooleanField(default=True)),
                ('valoracion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
